export const SET_SEARCH_QUERY = "SET_SEARCH_QUERY";
export const SET_SEARCH_PRODUCTS = "SET_SEARCH_PRODUCTS";
export const SET_CURRENT_PAGE_SEARCH = "SET_CURRENT_PAGE_SEARCH";
export const SEARCH_PRODUCTS_REQUEST = "SEARCH_PRODUCTS_REQUEST";
export const ADD_TO_WISHLIST_SEARCH = "ADD_PRODUCT_TO_WISHLIST"
export const REMOVE_FROM_WISHLIST_SEARCH = "REMOVE_PRODUCT_FROM_WISHLIST"