export const SET_SEARCH_QUERY = "SET_SEARCH_QUERY";
export const SET_SEARCH_PRODUCTS = "SET_SEARCH_PRODUCTS";
export const SET_CURRENT_PAGE_SEARCH = "SET_CURRENT_PAGE_SEARCH";
export const SEARCH_PRODUCTS_REQUEST = "SEARCH_PRODUCTS_REQUEST";