export const FETCH_ADMIN_PRODUCTS_REQUEST = "FETCH_ADMIN_PRODUCTS_REQUEST"
export const FETCH_ADMIN_PRODUCTS_SUCCESS = "FETCH_ADMIN_PRODUCTS_SUCCESS"
export const FETCH_ADMIN_PRODUCTS_FAILED = "FETCH_ADMIN_PRODUCTS_FAILED"