export const ADD_TO_CART = "ADD_TO_CART"
export const REMOVE_FROM_CART = "REMOVE_FROM_CART"
export const EMPTY_CART = "EMPTY_CART"
export const CART_FROM_DB = "CART_FROM_DB"
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM"