export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST";
export const REMOVE_FROM_WISHLIST = "REMOVE_FROM_WISHLIST";
export const GET_FULL_WISHLIST = "GET_FULL_WISHLIST";
export const SET_FULL_WISHLIST = "SET_FULL_WISHLIST";