export const FETCH_ADMIN_ORDERS_REQUEST = "FETCH_ADMIN_ORDERS_REQUEST"
export const FETCH_ADMIN_ORDERS_SUCCESS = "FETCH_ADMIN_ORDERS_SUCCESS"
export const FETCH_ADMIN_ORDERS_FAILED = "FETCH_ADMIN_ORDERS_FAILED"